# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce1dfbd875ff444650262a3cbd14f5fce652dccaad5e20c3ed8eb3d68270280d2e351074117cd3ba9ffab0341a3b3378a6e07417eb506415e8ab887540df5d6f

test:
  secret_key_base: 3fecccf45798962b7f9d0db71825eb55de53cf5b261342f649184d9e164bb248df18d9f05849f611add7c0ad153191c5fa49dc886b1e470dce09f1453cf97943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
